ALTER TABLE "Campaign" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "CampaignTemplate" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Contact" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Message" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "WorkspaceSettings" ALTER COLUMN "updatedAt" DROP DEFAULT;
